server {
    listen 80;

    # zadania do API przekierowywane do kontenera backendu
    location /api/ {
        proxy_pass http://backend:8080;
    }

    # statyczny frontend (SPA)
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}
