export const CYCLE_STATUS = ["PLANNED", "IMPLEMENTATION", "QA_TESTING", "UAT", "READY_FOR_PROD", "DEPLOYED", "CLOSED"];
export const TICKET_STATUS = ["TO_DO", "IN_PROGRESS", "CODE_REVIEW", "READY_FOR_QA", "QA_FAILED", "READY_FOR_UAT", "DONE"];
export const TICKET_TYPE = ["NEW_FEATURE", "ENHANCEMENT"];
export const BUG_PRIORITY = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
export const BUG_SOURCE = ["STATIC_ANALYSIS", "CODE_REVIEW", "SQA", "UAT"];
export const BUG_STATUS = ["NEW", "IN_PROGRESS", "VERIFIED"];
export const DEPLOYMENT_STATUS = ["NOT_CREATED", "PLANNED", "STARTED", "SUCCESS", "CRITICAL_FAILURE"];
export const UAT_STATUS = ["PENDING", "IN_PROGRESS", "ACCEPTED", "REJECTED"];
export const RN_VIEW_TYPE = ["INTERNAL", "UAT", "PRODUCTION"];

export type Row = Record<string, unknown>;
